Testing started at 12:53 ...
Launching unittests with arguments python -m unittest C:\Users\qinyu\OneDrive\Documents\GitHub\spring23-lab3-junzhu\src\test\testcase.py in C:\Users\qinyu\OneDrive\Documents\GitHub\spring23-lab3-junzhu\src\test

C:\Users\qinyu\AppData\Local\Programs\Python\Python310\lib\unittest\case.py:549: ResourceWarning: unclosed <socket.socket fd=568, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 59276), raddr=('127.0.0.1', 6060)>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\qinyu\AppData\Local\Programs\Python\Python310\lib\unittest\case.py:549: ResourceWarning: unclosed <socket.socket fd=452, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 59277), raddr=('127.0.0.1', 6060)>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\qinyu\AppData\Local\Programs\Python\Python310\lib\unittest\case.py:549: ResourceWarning: unclosed <socket.socket fd=448, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 59278), raddr=('127.0.0.1', 6060)>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\qinyu\AppData\Local\Programs\Python\Python310\lib\unittest\case.py:549: ResourceWarning: unclosed <socket.socket fd=584, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 59279), raddr=('127.0.0.1', 6060)>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback


Ran 7 tests in 0.065s

OK

Process finished with exit code 0
